### ISSUE TITLE
Improve Interface of the page

### ISSUE THREAD

**Issue by HimanshuSinghNegi** [Bauddhik-Geeks/Resource-Finder#87]
- Added Logo
- fixed some typos
![Screenshot (4)](https://user-images.githubusercontent.com/72004239/195871092-f2796e33-fe64-4add-a80b-75808af47d17.png)

**Comment by Nitesh-thapliyal** [comment]
@HimanshuSinghNegi great!

**Comment by Apurvapingale** [comment]
Hi please assign me this issue
